#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinAndroid.Resource", IsApplication=true)]

namespace XamarinAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Reactive.Bindings.Resource.String.ApplicationName = global::XamarinAndroid.Resource.String.ApplicationName;
			global::Reactive.Bindings.Resource.String.Hello = global::XamarinAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int ButtonAdd = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int ButtonListAdapter = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int ButtonReactivePropertyBasics = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int ButtonReplaceText = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int EditTextInput = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int TextViewAge = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int TextViewName = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int TextViewOutput = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textView3 = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListAdapterHeader = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListAdapterPersonTemplate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ReactivePropertyBasics = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
