// <copyright file="WebClientExtensionsTest.DownloadFileObservableAsync01.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.ComponentModel;
using System.Net;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using System.Collections.Specialized;
using System.Net.Cache;

namespace Codeplex.Reactive.Asynchronous
{
    public partial class WebClientExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(WebClientExtensionsTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void DownloadFileObservableAsync03()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      WebClient webClient;
      IObservable<AsyncCompletedEventArgs> iObservable;
      webClient = new WebClient();
      webClient.BaseAddress = "\u0100";
      webClient.Credentials = (ICredentials)null;
      webClient.Headers = (WebHeaderCollection)null;
      webClient.QueryString = (NameValueCollection)null;
      webClient.Proxy = (IWebProxy)null;
      webClient.CachePolicy = (RequestCachePolicy)null;
      ((Component)webClient).Site = (ISite)null;
      webClient.OpenWriteAsync((Uri)null, (string)null, (object)null);
      webClient.DownloadFile((Uri)null, (string)null);
      webClient.UploadFileAsync((Uri)null, (string)null, (string)null, (object)null);
      disposables.Add((IDisposable)webClient);
      iObservable =
        this.DownloadFileObservableAsync(webClient, (string)null, (string)null);
      disposables.Dispose();
    }
}
[TestMethod]
[PexGeneratedBy(typeof(WebClientExtensionsTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void DownloadFileObservableAsync0101()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      WebClient webClient;
      IObservable<AsyncCompletedEventArgs> iObservable;
      webClient = new WebClient();
      webClient.BaseAddress = "\u0100";
      webClient.Credentials = (ICredentials)null;
      webClient.Headers = (WebHeaderCollection)null;
      webClient.QueryString = (NameValueCollection)null;
      webClient.Proxy = (IWebProxy)null;
      webClient.CachePolicy = (RequestCachePolicy)null;
      ((Component)webClient).Site = (ISite)null;
      webClient.OpenWriteAsync((Uri)null, (string)null, (object)null);
      webClient.DownloadFile((Uri)null, (string)null);
      webClient.UploadFileAsync((Uri)null, (string)null, (string)null, (object)null);
      disposables.Add((IDisposable)webClient);
      iObservable =
        this.DownloadFileObservableAsync01(webClient, (Uri)null, (string)null);
      disposables.Dispose();
    }
}
    }
}
