// <copyright file="WebClientExtensionsTest.OpenWriteObservableAsync.g.cs" company="Microsoft">Copyright © Microsoft 2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using System.Net;
using System.Collections.Specialized;
using System.Net.Cache;
using System.ComponentModel;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Codeplex.Reactive.Asynchronous
{
    public partial class WebClientExtensionsTest
    {
    }
}
