// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Codeplex.Reactive.Asynchronous
{
    public partial class StreamExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void WriteAsObservableAndSubscribe57()
{
    this.WriteAsObservableAndSubscribe("");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void WriteAsObservableAndSubscribe295()
{
    this.WriteAsObservableAndSubscribe("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void WriteAsObservableAndSubscribe480()
{
    this.WriteAsObservableAndSubscribe("\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void WriteAsObservableAndSubscribe950()
{
    this.WriteAsObservableAndSubscribe("\ud801\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void WriteAsObservableAndSubscribe22()
{
    this.WriteAsObservableAndSubscribe("\ud9c0\udc00");
}
    }
}
