// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.IO;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Codeplex.Reactive.Asynchronous
{
    public partial class StreamExtensionsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void ReadAsObservableAndSubscribe57()
{
    this.ReadAsObservableAndSubscribe("");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void ReadAsObservableAndSubscribe295()
{
    this.ReadAsObservableAndSubscribe("\0");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void ReadAsObservableAndSubscribe418()
{
    this.ReadAsObservableAndSubscribe("\udc00");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void ReadAsObservableAndSubscribe41()
{
    this.ReadAsObservableAndSubscribe("\0\uc000\0\0\0\0\0\0\0\0\0\0\0\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void ReadAsObservableAndSubscribe950()
{
    this.ReadAsObservableAndSubscribe("\ud801\0\0");
}
[TestMethod]
[PexGeneratedBy(typeof(StreamExtensionsTest))]
public void ReadAsObservableAndSubscribe22()
{
    this.ReadAsObservableAndSubscribe("\ud9c0\udc00");
}
    }
}
