// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Codeplex.Reactive.Notifier
{
    public partial class SignalNotifierTest
    {
[TestMethod]
[PexGeneratedBy(typeof(SignalNotifierTest))]
[ExpectedException(typeof(ArgumentException))]
public void DecrementThrowsArgumentException556()
{
    this.Decrement(1, 1, 0);
}
[TestMethod]
[PexGeneratedBy(typeof(SignalNotifierTest))]
[PexRaisedException(typeof(AssertFailedException))]
public void DecrementThrowsAssertFailedException652()
{
    this.Decrement(514, 3, 1);
}
[TestMethod]
[PexGeneratedBy(typeof(SignalNotifierTest))]
[PexRaisedException(typeof(AssertFailedException))]
public void DecrementThrowsAssertFailedException57()
{
    this.Decrement(1023, 1022, 1022);
}
    }
}
